### ISSUE TITLE
Custom Dataset Preprocessing: molecular_graph referenced before assignment

### ISSUE THREAD

**Issue by sw5park** [MolecularAI/GraphINVENT#21]
Hello @rociomer, thank you very much for this work!

- Objective: Preprocess custom dataset 
- Issue: local variable 'molecular_graph' referenced before assignment

**Error:**
* Running job as a normal process.
/home/epark03/miniconda3/envs/graphinvent/bin/python
* Run mode: 'preprocess'
* Preprocessing test data.
Traceback (most recent call last):
  File "./graphinvent/main.py", line 76, in <module>
    main()
  File "./graphinvent/main.py", line 41, in main
    workflow.preprocess_phase()
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/Workflow.py", line 313, in preprocess_phase
    self.preprocess_test_data()
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/Workflow.py", line 86, in preprocess_test_data
    test_set_preprocesser = DataProcesser(path=self.constants.test_set)
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/DataProcesser.py", line 56, in __init__
    self.total_n_subgraphs = self.get_n_subgraphs()
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/DataProcesser.py", line 383, in get_n_subgraphs
    for molecular_graph in molecular_graph_generator:
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/DataProcesser.py", line 339, in get_graph
    return molecular_graph
**UnboundLocalError: local variable 'molecular_graph' referenced before assignment**
Traceback (most recent call last):
  File "submit-pre-training.py", line 220, in <module>
    submit()
  File "submit-pre-training.py", line 146, in submit
    subprocess.run([f"{PYTHON_PATH}",
  File "/home/epark03/miniconda3/envs/graphinvent/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError

**Comment by sw5park** [comment]
@rociomer I have since fixed the issue, but am met with another error during hdf5 file generation during preprocessing:


**Issue: IndexError: list index out of range**

Traceback (most recent call last):
  File "./graphinvent/main.py", line 76, in <module>
    main()
  File "./graphinvent/main.py", line 41, in main
    workflow.preprocess_phase()
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/Workflow.py", line 315, in preprocess_phase
    self.preprocess_train_data()
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/Workflow.py", line 98, in preprocess_train_data
    train_set_preprocesser.preprocess()f
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/DataProcesser.py", line 94, in preprocess
    self.get_subgraphs(init_idx=idx)
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/DataProcesser.py", line 266, in get_subgraphs
    self.get_ts_properties(molecular_graphs=molecular_graph_list,
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/DataProcesser.py", line 416, in get_ts_properties
    ts_properties = analyzer.evaluate_training_set(
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/Analyzer.py", line 305, in evaluate_training_set
    training_set_properties = self.get_molecular_properties(
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/Analyzer.py", line 553, in get_molecular_properties
    _get_node_feature_distribution(molecular_graphs=molecules)
  File "/home/epark03/eric_dev/scaffold-generation/GraphINVENT/graphinvent/Analyzer.py", line 422, in _get_node_feature_distribution
    if isinstance(molecular_graphs[0].node_features, torch.Tensor):
IndexError: list index out of range
Traceback (most recent call last):
  File "submit-pre-training.py", line 220, in <module>
    submit()
  File "submit-pre-training.py", line 146, in submit
    subprocess.run([f"{PYTHON_PATH}",
  File "/home/epark03/miniconda3/envs/graphinvent/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/epark03/miniconda3/envs/graphinvent/bin/python', './graphinvent/main.py', '--job-dir', '/home/epark03/eric_dev/scaffold-generation/GraphINVENT/output_pth/pth/job_0/']' returned non-zero exit status 1.
