### ISSUE TITLE
errors on tensorboard

### ISSUE THREAD

**Issue by xuzhang5788** [MolecularAI/GraphINVENT#5]
Thank you for your repo. When I followed your tutorials, I met a difficulty on tensorboard.
I ran $python submit.py
I got:
* Creating dataset directory ./output_gdb13_1K/example/
* Creating model subdirectory ./output_gdb13_1K/example/job_0/
* Running job as a normal process.
/home/xzhang/miniconda3/envs/graphinvent/bin/python
* Running job using HDF datasets located at ./data/gdb13_1K/
* Checking that the relevant parameters match those used in preprocessing the dataset.
-- Job parameters match preprocessing parameters.
Traceback (most recent call last):
  File "./graphinvent/main.py", line 5, in <module>
    import util
  File "/home/xzhang/projects/GraphINVENT/graphinvent/util.py", line 20, in <module>
    tb_writer = SummaryWriter(log_dir=constants.tensorboard_dir, flush_secs=10)
  File "/home/xzhang/.local/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 220, in __init__
    self._get_file_writer()
  File "/home/xzhang/.local/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 250, in _get_file_writer
    self.file_writer = FileWriter(self.log_dir, self.max_queue,
  File "/home/xzhang/.local/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 60, in __init__
    self.event_writer = EventFileWriter(
  File "/home/xzhang/miniconda3/envs/graphinvent/lib/python3.8/site-packages/tensorboard/summary/writer/event_file_writer.py", line 73, in __init__
    if not tf.io.gfile.exists(logdir):
  File "/home/xzhang/miniconda3/envs/graphinvent/lib/python3.8/site-packages/tensorboard/lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
AttributeError: module 'tensorflow' has no attribute 'io'
-- Sleeping 2 seconds.

I reinstalled tensorboard, it still didn't work.

**Comment by xuzhang5788** [comment]
It worked after I installed tensorflow-io
pip install tensorflow-io

**Comment by xuzhang5788** [comment]
But how to use tensorborad? Could you please give me some instructions or show me what you got from the tensorboard? Many thanks

**Comment by rociomer** [comment]
To run a tensorboard session from a local machine, type:

```
tensorboard --logdir path/to/tensorboard_dir/
```

So, for instance, if you want to view all the tensorboard logs in projects/GraphINVENT/output_gdb13_1K/tensorboard/, you can run:

```
tensorboard --logdir projects/GraphINVENT/output_gdb13_1K/tensorboard/
```

If you have the tensorboard logs on a remote machine, you can view them as per the instructions here: https://github.com/rociomer/cheat-sheets/blob/master/tensorboard.md

The tensorboard logs should look as they do on this page: 
https://www.tensorflow.org/tensorboard/get_started
but with the relevant GraphINVENT metrics, e.g., training and validation losses for the generative models, fraction of valid generated molecules, etc.

Does this help? Apologies for the late response.
